# Generated by Django 4.2.3 on 2023-08-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table='tblevents',
        ),
    ]
