# Generated by Django 4.2.3 on 2023-08-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0002_alter_events_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
