# Generated by Django 4.2.3 on 2023-08-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
