# Generated by Django 4.2.3 on 2023-07-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='notification_mode',
            field=models.CharField(choices=[('email', 'Email'), (None, 'None'), ('both', 'Both'), ('sms', 'SMS')], default=None, max_length=5),
        ),
    ]
