# Generated by Django 4.2.3 on 2023-07-30 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_alter_reminder_notification_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='notification_mode',
            field=models.CharField(choices=[(None, 'None'), ('email', 'Email'), ('sms', 'SMS'), ('both', 'Both')], default=None, max_length=5),
        ),
    ]
