# Generated by Django 4.2.3 on 2023-07-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_alter_reminder_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='notification_mode',
            field=models.CharField(choices=[('sms', 'SMS'), ('both', 'Both'), (None, 'None'), ('email', 'Email')], default=None, max_length=5),
        ),
    ]
