# Generated by Django 4.2.3 on 2023-07-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_alter_reminder_notification_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='notification_mode',
            field=models.CharField(choices=[(None, 'None'), ('email', 'Email'), ('sms', 'SMS'), ('both', 'Both')], default=None, max_length=5),
        ),
    ]
