# Generated by Django 4.2.3 on 2023-08-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_alter_reminder_notification_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='notification_mode',
            field=models.CharField(choices=[('email', 'Email'), ('None', 'None'), ('both', 'Both'), ('sms', 'SMS')], default=None, max_length=5),
        ),
    ]
