# Generated by Django 4.2.3 on 2023-08-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0008_alter_reminder_notification_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='notification_mode',
            field=models.CharField(choices=[('None', 'None'), ('sms', 'SMS'), ('email', 'Email'), ('both', 'Both')], default=None, max_length=5),
        ),
    ]
