# Generated by Django 4.2.3 on 2023-08-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0014_alter_reminder_notification_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='notification_mode',
            field=models.CharField(choices=[('sms', 'SMS'), ('None', 'None'), ('both', 'Both'), ('email', 'Email')], default=None, max_length=5),
        ),
    ]
