# Generated by Django 4.2.3 on 2023-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0020_alter_reminder_notification_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='notification_mode',
            field=models.CharField(choices=[('both', 'Both'), ('sms', 'SMS'), ('email', 'Email'), ('None', 'None')], default=None, max_length=5),
        ),
    ]
