# Generated by Django 4.2.3 on 2023-09-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0021_alter_reminder_notification_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='notification_mode',
            field=models.CharField(choices=[('None', 'None'), ('email', 'Email')], default=None, max_length=5),
        ),
    ]
