# Generated by Django 4.2.3 on 2023-10-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0022_alter_reminder_notification_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
