# Generated by Django 4.2.3 on 2023-08-16 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('notification_mode', models.CharField(choices=[('email', 'Email'), ('None', 'None'), ('sms', 'SMS'), ('both', 'Both')], default=None, max_length=5)),
                ('category', models.CharField(choices=[('savings', 'Savings'), ('health and fitness', 'Health & Fitness'), ('travel and vacation', 'Travel & Vacation'), ('home and family', 'Home & Family'), ('educational', 'Educational'), ('other', 'Other'), ('spendings', 'Spendings'), ('personal development', 'Personal Development'), ('career and buisness', 'Career & Buisness'), ('entertainment', 'Entertainment')])),
                ('complete_amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
