# Generated by Django 4.2.3 on 2023-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('travel and vacation', 'Travel & Vacation'), ('health and fitness', 'Health & Fitness'), ('career and buisness', 'Career & Buisness'), ('spendings', 'Spendings'), ('educational', 'Educational'), ('entertainment', 'Entertainment'), ('savings', 'Savings'), ('personal development', 'Personal Development'), ('other', 'Other'), ('home and family', 'Home & Family')]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='notification_mode',
            field=models.CharField(choices=[('both', 'Both'), ('None', 'None'), ('sms', 'SMS'), ('email', 'Email')], default=None, max_length=5),
        ),
    ]
