# Generated by Django 4.2.3 on 2023-09-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_alter_goal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('health and fitness', 'Health & Fitness'), ('entertainment', 'Entertainment'), ('home and family', 'Home & Family'), ('educational', 'Educational'), ('other', 'Other'), ('travel and vacation', 'Travel & Vacation'), ('spendings', 'Spendings'), ('savings', 'Savings'), ('career and buisness', 'Career & Buisness'), ('personal development', 'Personal Development')]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='notification_mode',
            field=models.CharField(choices=[('both', 'Both'), ('sms', 'SMS'), ('email', 'Email'), ('None', 'None')], default=None, max_length=5),
        ),
    ]
