# Generated by Django 4.2.3 on 2023-09-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0004_alter_goal_category_alter_goal_notification_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('savings', 'Savings'), ('travel and vacation', 'Travel & Vacation'), ('career and buisness', 'Career & Buisness'), ('educational', 'Educational'), ('home and family', 'Home & Family'), ('personal development', 'Personal Development'), ('health and fitness', 'Health & Fitness'), ('spendings', 'Spendings'), ('other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='notification_mode',
            field=models.CharField(choices=[('sms', 'SMS'), ('None', 'None'), ('email', 'Email'), ('both', 'Both')], default=None, max_length=5),
        ),
    ]
