# Generated by Django 4.2.3 on 2023-09-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0007_alter_goal_category_alter_goal_notification_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('travel and vacation', 'Travel & Vacation'), ('health and fitness', 'Health & Fitness'), ('educational', 'Educational'), ('spendings', 'Spendings'), ('home and family', 'Home & Family'), ('personal development', 'Personal Development'), ('career and buisness', 'Career & Buisness'), ('other', 'Other'), ('entertainment', 'Entertainment'), ('savings', 'Savings')]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='notification_mode',
            field=models.CharField(choices=[('None', 'None'), ('email', 'Email')], default=None, max_length=5),
        ),
    ]
