# Generated by Django 4.2.3 on 2023-10-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0008_alter_goal_category_alter_goal_notification_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('personal development', 'Personal Development'), ('other', 'Other'), ('savings', 'Savings'), ('home and family', 'Home & Family'), ('travel and vacation', 'Travel & Vacation'), ('career and buisness', 'Career & Buisness'), ('spendings', 'Spendings'), ('health and fitness', 'Health & Fitness'), ('educational', 'Educational')]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='notification_mode',
            field=models.CharField(choices=[('email', 'Email'), ('None', 'None')], default=None, max_length=5),
        ),
    ]
