# Generated by Django 4.2.3 on 2024-06-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0009_alter_goal_category_alter_goal_notification_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('educational', 'Educational'), ('other', 'Other'), ('career and buisness', 'Career & Buisness'), ('travel and vacation', 'Travel & Vacation'), ('savings', 'Savings'), ('spendings', 'Spendings'), ('home and family', 'Home & Family'), ('personal development', 'Personal Development'), ('entertainment', 'Entertainment'), ('health and fitness', 'Health & Fitness')]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='notification_mode',
            field=models.CharField(choices=[('None', 'None'), ('email', 'Email')], default=None, max_length=5),
        ),
    ]
